# Interrupt Setup, Triggered By FPGA IRQ
# IRQ 0
# Loop Period (type int) of the main loop, where controllers were implemented
MainLoop_period_us: 1000
# IRQ 1
# Loop Period (type int) of the loop handling CAN transceiving, at least 1000 us
CANLoop_period_us: 1000
# CAN Bus timeout
CAN_Timeout_us: 1000

# Measure hall calibration offset
# Set to 1 when measuring the offset value of each module
Measure_offset: 0
Hall_calibration_vel: 0.5
Hall_calibration_tol: 0.005

# MOD A Bias represented in radian
LF_Module:
  Enable: 1
  CAN_PORT: "MOD1CAN0"
  Motor_R:
    FW_Version: 3
    CAN_ID: 1
    Calibration_Bias: 0.021583
    KP: 85
    KI: 0
    KD: 1.75
    KT: 2.04
    Torque_Feedfoward: 0
  Motor_L:
    FW_Version: 3
    CAN_ID: 2
    Calibration_Bias: -0.85281
    KP: 85
    KI: 0
    KD: 1.75
    KT: 2.148
    Torque_Feedfoward: 0 
  Motor_H:
    FW_Version: 3
    CAN_ID: 3
    # TODO: Update Calibration Bias,KP,KI,KD,KT,Torque_Feedfoward
    Calibration_Bias: 0
    KP: 85
    KI: 0
    KD: 1.75
    KT: 2.148
    Torque_Feedfoward: 0 

# MOD B
RF_Module:
  Enable: 0
  CAN_PORT: "MOD1CAN1"
  Motor_R:
    FW_Version: 3
    CAN_ID: 1
    Calibration_Bias: 0.878694
    KP: 85
    KI: 0
    KD: 1.75
    KT: 2.132
    Torque_Feedfoward: 0
  Motor_L:
    FW_Version: 3
    CAN_ID: 2
    Calibration_Bias: -0.021583
    KP: 85
    KI: 0
    KD: 1.75
    KT: 2.185
    Torque_Feedfoward: 0
  Motor_H:
    FW_Version: 3
    CAN_ID: 3
    # TODO: Update Calibration Bias,KP,KI,KD,KT,Torque_Feedfoward
    Calibration_Bias: 0
    KP: 85
    KI: 0
    KD: 1.75
    KT: 2.148
    Torque_Feedfoward: 0 

# MOD C
RH_Module:
  Enable: 0
  CAN_PORT: "MOD2CAN0"
  Motor_R:
    FW_Version: 3
    CAN_ID: 1
    Calibration_Bias: 0.021583
    KP: 85
    KI: 0
    KD: 1.75
    KT: 1.928
    Torque_Feedfoward: 0
  Motor_L:
    FW_Version: 3
    CAN_ID: 2
    Calibration_Bias: -0.85856
    KP: 85
    KI: 0
    KD: 1.75
    KT: 2.062
    Torque_Feedfoward: 0
  Motor_H:
    FW_Version: 3
    CAN_ID: 3
    # TODO: Update Calibration Bias,KP,KI,KD,KT,Torque_Feedfoward
    Calibration_Bias: 0
    KP: 85
    KI: 0
    KD: 1.75
    KT: 2.148
    Torque_Feedfoward: 0 

# MOD D
LH_Module:
  Enable: 0
  CAN_PORT: "MOD2CAN1"
  Motor_R:
    FW_Version: 3
    CAN_ID: 1
    Calibration_Bias: 0.855688
    KP: 85
    KI: 0
    KD: 1.75
    KT: 2.105
    Torque_Feedfoward: 0
  Motor_L:
    FW_Version: 3
    CAN_ID: 2
    Calibration_Bias: -0.021583
    KP: 85
    KI: 0
    KD: 1.75
    KT: 2.146
    Torque_Feedfoward: 0
  Motor_H:
    FW_Version: 3
    CAN_ID: 3
    # TODO: Update Calibration Bias,KP,KI,KD,KT,Torque_Feedfoward
    Calibration_Bias: 0
    KP: 85
    KI: 0
    KD: 1.75
    KT: 2.148
    Torque_Feedfoward: 0 
    
# ADD USED MODULE IN LIST
Number_of_modules: 4
Modules_list:
  0: LF_Module
  1: RF_Module
  2: RH_Module
  3: LH_Module
# TODO: Test CH1 powerboard scaling factor values and update the yaml file accordingly
Powerboard1_Scaling_Factor:
  - # 1 Power Battery
    Current_Factor: 0.0051
    Current_Offset: -2.5371
    Voltage_Factor: 0.0155
    Voltage_Offset: 0.9189
  - # 2 CPU SBRIO, ORIN
    Current_Factor: 0.0051
    Current_Offset: -2.5371
    Voltage_Factor: 0.0155
    Voltage_Offset: 0.1208
  - # 3 SPARE 1
    Current_Factor: 0.005
    Current_Offset: -2.4846
    Voltage_Factor: 0.0154
    Voltage_Offset: 0.097
  - # 4 SPARE 2
    Current_Factor: 0.005
    Current_Offset: -2.5005
    Voltage_Factor: 0.0154
    Voltage_Offset: 0.0432
  - # 5 Module 1
    Current_Factor: 0.005
    Current_Offset: -2.4557
    Voltage_Factor: 0.0154
    Voltage_Offset: 0.0999
  - # 6 Module 2
    Current_Factor: 0.005
    Current_Offset: -2.484
    Voltage_Factor: 0.0154
    Voltage_Offset: 0.0602
  - # 7 Module 3
    Current_Factor: 0.0051
    Current_Offset: -2.5123
    Voltage_Factor: 0.0153
    Voltage_Offset: 0.1868
  - # 8 Module 4
    Current_Factor: 0.005
    Current_Offset: -2.4624
    Voltage_Factor: 0.0154
    Voltage_Offset: 0.0462
# TODO: Test CH1 powerboard scaling factor values and update the yaml file accordingly
Powerboard2_Scaling_Factor:
  - # 1 Power Battery
    Current_Factor: 0.005
    Current_Offset: -2.4829
    Voltage_Factor: 0.0155
    Voltage_Offset: 0.9364
  - # 2 CPU SBRIO, ORIN
    Current_Factor: 0.005
    Current_Offset: -2.4829
    Voltage_Factor: 0.0156
    Voltage_Offset: 0.2937
  - # 3 SPARE 1
    Current_Factor: 0.0048
    Current_Offset: -2.3876
    Voltage_Factor: 0.0155
    Voltage_Offset: 0.2787
  - # 4 SPARE 2
    Current_Factor: 0.0049
    Current_Offset: -2.4423
    Voltage_Factor: 0.0155
    Voltage_Offset: 0.2941
  - # 5 Module 1
    Current_Factor: 0.005
    Current_Offset: -2.4694
    Voltage_Factor: 0.0152
    Voltage_Offset: 0.1799
  - # 6 Module 2
    Current_Factor: 0.005
    Current_Offset: -2.4797
    Voltage_Factor: 0.0155
    Voltage_Offset: 0.1714
  - # 7 Module 3
    Current_Factor: 0.005
    Current_Offset: -2.5045
    Voltage_Factor: 0.0154
    Voltage_Offset: 0.2708
  - # 8 Module 4
    Current_Factor: 0.005
    Current_Offset: -2.4955
    Voltage_Factor: 0.0153
    Voltage_Offset: 0.2677
